server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # Handle React Router paths
        try_files $uri $uri/ /index.html;
    }

    # Proxy API requests to backend
    location /api/ {
        # remove the /api prefix before forwarding
        rewrite ^/api/(.*)$ /$1 break;
        proxy_pass http://sair-cpa-api.duckdns.org;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
